	ren jconfig.vc jconfig.h
	ren makejdsw.vc6 jpeg.dsw
	ren makeadsw.vc6 apps.dsw
	ren makejmak.vc6 jpeg.mak
	ren makejdep.vc6 jpeg.dep
	ren makejdsp.vc6 jpeg.dsp
	ren makecmak.vc6 cjpeg.mak
	ren makecdep.vc6 cjpeg.dep
	ren makecdsp.vc6 cjpeg.dsp
	ren makedmak.vc6 djpeg.mak
	ren makeddep.vc6 djpeg.dep
	ren makeddsp.vc6 djpeg.dsp
	ren maketmak.vc6 jpegtran.mak
	ren maketdep.vc6 jpegtran.dep
	ren maketdsp.vc6 jpegtran.dsp
	ren makermak.vc6 rdjpgcom.mak
	ren makerdep.vc6 rdjpgcom.dep
	ren makerdsp.vc6 rdjpgcom.dsp
	ren makewmak.vc6 wrjpgcom.mak
	ren makewdep.vc6 wrjpgcom.dep
	ren makewdsp.vc6 wrjpgcom.dsp
